---
builds:
  - main
  - slim

options:
  common: "-Duseshrplib -Dvendorprefix=/usr/local"
  threaded: "-Dusethreads"

releases:
  - version: 5.43.4
    sha256:  75676cc02c1d4d6f4577f7fd953e07ab5d06f71cf4201753ab6e2b0ddb5a4931
    extra_flags: "-Dusedevel -Dversiononly=undef"
    debian_release:
      - bullseye
      - bookworm
      - trixie

  - version: 5.38.5
    sha256:  b7667d3ff309068852af7853910aaccec26c839d717402121b664ac705e07bfe
    debian_release:
      - bullseye
      - bookworm
      - trixie

  - version: 5.40.3
    sha256:  4c155b4e6160682b38919b55ac319081b898db11857cf18a7d9ffed2648ccaff
    debian_release:
      - bullseye
      - bookworm
      - trixie

  - version: 5.42.0
    sha256: e093ef184d7f9a1b9797e2465296f55510adb6dab8842b0c3ed53329663096dc
    debian_release:
      - bullseye
      - bookworm
      - trixie
